<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Document extends Model
{
    use HasUuids, SoftDeletes;

    protected $primaryKey = 'uid';
    public $incrementing = false;

    protected $fillable = [
        'uid',
        'event_uid',
        'name',
        'type',
        'title',
        'description',
        'logo_left',
        'logo_right',
        'data_source',
        'selected_columns',
        'layout_settings',
        'content',
        'file_path',
        'export_format',
        'is_public',
        'total_price',
        'font_family',
        'font_size',
        'page_size',
        'page_orientation',
    ];

    protected $casts = [
        'selected_columns' => 'array',
        'layout_settings' => 'array',
        'is_public' => 'boolean',
        'total_price' => 'decimal:2',
    ];

    public function event()
    {
        return $this->belongsTo(Event::class, 'event_uid', 'uid');
    }

    /**
     * Get default layout settings structure.
     */
    public static function defaultLayout(): array
    {
        return [
            'page' => ['size' => 'A4', 'orientation' => 'portrait'],
            'header' => ['show' => true, 'show_logo_left' => true, 'show_logo_right' => true],
            'table' => ['show_border' => true, 'zebra' => true, 'font_size' => '10'],
            'footer' => ['show' => true, 'text' => 'Generated by Swimming Club Management System'],
        ];
    }

    /**
     * Available data sources and their columns definition.
     */
    public static function dataSources(): array
    {
        return [
            'results' => [
                'label' => 'Hasil Lomba',
                'icon' => '🏆',
                'desc' => 'Ranking, waktu, dan poin atlet',
                'columns' => [
                    ['key' => 'rank', 'label' => 'Peringkat'],
                    ['key' => 'athlete_name', 'label' => 'Nama Atlet'],
                    ['key' => 'club_name', 'label' => 'Nama Klub'],
                    ['key' => 'category', 'label' => 'Kategori'],
                    ['key' => 'style', 'label' => 'Gaya Renang'],
                    ['key' => 'time', 'label' => 'Waktu'],
                    ['key' => 'points', 'label' => 'Poin'],
                    ['key' => 'notes', 'label' => 'Catatan'],
                ],
            ],
            'schedules' => [
                'label' => 'Jadwal / Buku Acara',
                'icon' => '📅',
                'desc' => 'Seri, lintasan, dan heat',
                'columns' => [
                    ['key' => 'lane', 'label' => 'Lintasan'],
                    ['key' => 'athlete_name', 'label' => 'Nama Lengkap Atlet'],
                    ['key' => 'birth_year', 'label' => 'Tahun Lahir'],
                    ['key' => 'club_name', 'label' => 'Tim/Club'],
                    ['key' => 'seed_time', 'label' => 'Prestasi'],
                    ['key' => 'result', 'label' => 'Hasil'],
                    ['key' => 'heat', 'label' => 'Seri'],
                ],
            ],
            'registrations' => [
                'label' => 'Pendaftaran',
                'icon' => '📋',
                'desc' => 'Data peserta yang terdaftar',
                'columns' => [
                    ['key' => 'no', 'label' => 'No'],
                    ['key' => 'athlete_name', 'label' => 'Nama Atlet'],
                    ['key' => 'birth_year', 'label' => 'Tahun Lahir'],
                    ['key' => 'club_name', 'label' => 'Tim/Club'],
                    ['key' => 'category', 'label' => 'Kategori'],
                    ['key' => 'status', 'label' => 'Status'],
                    ['key' => 'seed_time', 'label' => 'Prestasi (Seed)'],
                ],
            ],
            'payments' => [
                'label' => 'Pembayaran / Invoice',
                'icon' => '💰',
                'desc' => 'Keuangan dan transaksi',
                'columns' => [
                    ['key' => 'no', 'label' => 'No'],
                    ['key' => 'invoice_no', 'label' => 'No Invoice'],
                    ['key' => 'club_name', 'label' => 'Nama Klub'],
                    ['key' => 'total', 'label' => 'Total Bayar'],
                    ['key' => 'method', 'label' => 'Metode'],
                    ['key' => 'status', 'label' => 'Status'],
                    ['key' => 'date', 'label' => 'Tanggal'],
                ],
            ],
            'clubs' => [
                'label' => 'Data Klub',
                'icon' => '🏢',
                'desc' => 'Informasi institusi',
                'columns' => [
                    ['key' => 'no', 'label' => 'No'],
                    ['key' => 'club_name', 'label' => 'Nama Klub'],
                    ['key' => 'coach', 'label' => 'Pelatih'],
                    ['key' => 'total_athletes', 'label' => 'Jumlah Atlet'],
                    ['key' => 'phone', 'label' => 'Telepon'],
                    ['key' => 'address', 'label' => 'Alamat'],
                ],
            ],
            'events' => [
                'label' => 'Data Event',
                'icon' => '🎯',
                'desc' => 'Informasi event lomba',
                'columns' => [
                    ['key' => 'no', 'label' => 'No'],
                    ['key' => 'event_name', 'label' => 'Nama Event'],
                    ['key' => 'date', 'label' => 'Tanggal'],
                    ['key' => 'location', 'label' => 'Lokasi'],
                    ['key' => 'status', 'label' => 'Status'],
                    ['key' => 'total_categories', 'label' => 'Jumlah Lomba'],
                ],
            ],
        ];
    }
}
