<?php

use Livewire\Volt\Component;
use App\Models\Document;
use Illuminate\Support\Str;
use Livewire\WithPagination;
use Livewire\WithFileUploads;

new class extends Component {
    use WithPagination, WithFileUploads;

    public $search = '';
    public $name = '';
    public $type = 'other';
    public $title = '';
    public $description = '';
    public $content = '';
    public $is_public = true;
    public $data_source = '';
    public $selected_columns = [];
    public $font_family = 'Arial';
    public $font_size = 10;
    public $page_size = 'A4';
    public $page_orientation = 'portrait';
    public $layout_settings = [
        'page' => ['size' => 'A4', 'orientation' => 'portrait'],
        'header' => ['show' => true, 'show_logo_left' => true, 'show_logo_right' => true],
        'table' => ['show_border' => true, 'zebra' => true, 'columns' => []],
        'footer' => ['show' => true, 'text' => 'Generated by KSC System']
    ];
    public $activeTab = 'general'; // general, content, data_builder, layout, preview

    public $logo_left = null;
    public $logo_right = null;
    public $existingLogoLeft = null;
    public $existingLogoRight = null;
    
    public $editingDocumentId = null;
    public $documentToDelete = null;
    public $showModal = false;
    public $showDeleteModal = false;
    public $modalMode = 'create';

    public function with()
    {
        $documentsQuery = Document::query()
            ->whereNull('event_uid');

        if ($this->search) {
            $documentsQuery->where(function($q) {
                $q->where('name', 'like', '%' . $this->search . '%')
                  ->orWhere('title', 'like', '%' . $this->search . '%')
                  ->orWhere('type', 'like', '%' . $this->search . '%');
            });
        }

        // Available columns = all columns minus already selected
        $availableColumns = [];
        if ($this->data_source) {
            $sources = Document::dataSources();
            $all = $sources[$this->data_source]['columns'] ?? [];
            $chosenKeys = collect($this->selected_columns)->pluck('key')->toArray();
            $availableColumns = array_values(array_filter($all, fn($c) => !in_array($c['key'], $chosenKeys)));
        }

        return [
            'documents' => $documentsQuery->latest()->paginate(10),
            'dataSources' => Document::dataSources(),
            'availableColumns' => $availableColumns,
        ];
    }

    public function openCreateModal()
    {
        $this->reset(['name', 'type', 'title', 'description', 'content', 'is_public', 'logo_left', 'logo_right', 'existingLogoLeft', 'existingLogoRight', 'editingDocumentId', 'data_source', 'selected_columns', 'font_family', 'font_size', 'page_size', 'page_orientation']);
        $this->font_family = 'Arial';
        $this->font_size = 10;
        $this->page_size = 'A4';
        $this->page_orientation = 'portrait';
        $this->layout_settings = [
            'page' => ['size' => 'A4', 'orientation' => 'portrait'],
            'header' => ['show' => true, 'show_logo_left' => true, 'show_logo_right' => true],
            'table' => ['show_border' => true, 'zebra' => true, 'columns' => []],
            'footer' => ['show' => true, 'text' => 'Generated by KSC System']
        ];
        $this->activeTab = 'general';
        $this->modalMode = 'create';
        $this->showModal = true;
    }

    public function openEditModal($uid)
    {
        $document = Document::where('uid', $uid)->firstOrFail();
        $this->editingDocumentId = $document->uid;
        $this->name = $document->name;
        $this->type = $document->type;
        $this->title = $document->title;
        $this->description = $document->description;
        $this->content = $document->content;
        $this->is_public = $document->is_public;
        $this->font_family = $document->font_family ?? 'Arial';
        $this->font_size = $document->font_size ?? 10;
        $this->page_size = $document->page_size ?? 'A4';
        $this->page_orientation = $document->page_orientation ?? 'portrait';

        $ls = $document->layout_settings ?? $this->layout_settings;
        $this->data_source = $ls['data_source'] ?? '';
        $this->selected_columns = $ls['table']['columns'] ?? [];
        $this->layout_settings = $ls;
        $this->existingLogoLeft = $document->logo_left;
        $this->existingLogoRight = $document->logo_right;
        
        $this->activeTab = 'general';
        $this->modalMode = 'edit';
        $this->showModal = true;
    }

    public function save()
    {
        $this->authorize($this->modalMode === 'create' ? 'setting-document.create' : 'setting-document.edit');

        $this->validate([
            'name' => 'required|string|max:255',
            'type' => 'required|string|max:100',
            'title' => 'nullable|string|max:255',
            'description' => 'nullable|string',
            'content' => 'nullable|string',
            'is_public' => 'boolean',
            'logo_left' => 'nullable|string',
            'logo_right' => 'nullable|string',
        ]);

        $data = [
            'name' => $this->name,
            'type' => $this->type,
            'title' => $this->title,
            'description' => $this->description,
            'content' => $this->content,
            'is_public' => $this->is_public,
            'font_family' => $this->font_family,
            'font_size' => $this->font_size,
            'page_size' => $this->page_size,
            'page_orientation' => $this->page_orientation,
            'layout_settings' => array_merge($this->layout_settings, [
                'data_source' => $this->data_source,
                'page' => [
                    'size' => $this->page_size,
                    'orientation' => $this->page_orientation
                ],
                'table' => array_merge($this->layout_settings['table'], [
                    'columns' => $this->selected_columns,
                    'font_size' => $this->font_size,
                ]),
            ]),
            'event_uid' => null, // Global template
        ];

        if ($this->logo_left) {
            $data['logo_left'] = ImageHelper::uploadToWebp($this->logo_left, 'documents/logos', $this->existingLogoLeft);
        }

        if ($this->logo_right) {
            $data['logo_right'] = ImageHelper::uploadToWebp($this->logo_right, 'documents/logos', $this->existingLogoRight);
        }

        if ($this->modalMode === 'create') {
            $data['uid'] = (string) Str::uuid();
            Document::create($data);
            $message = 'Format dokumen berhasil ditambahkan';
        } else {
            $document = Document::where('uid', $this->editingDocumentId)->firstOrFail();
            $document->update($data);
            $message = 'Format dokumen berhasil diperbarui';
        }

        $this->showModal = false;
        $this->dispatch('notification', [
            'status' => 'success',
            'message' => $message
        ]);
    }

    public function confirmDelete($uid)
    {
        $this->documentToDelete = Document::where('uid', $uid)->firstOrFail();
        $this->showDeleteModal = true;
    }

    public function delete()
    {
        $this->authorize('setting-document.delete');

        if ($this->documentToDelete) {
            $this->documentToDelete->delete();
            $this->showDeleteModal = false;
            $this->documentToDelete = null;
            $this->dispatch('notification', [
                'status' => 'success',
                'message' => 'Format dokumen berhasil dihapus'
            ]);
        }
    }

    // === DATA BUILDER METHODS ===

    public function selectSource($key)
    {
        $this->data_source = $key;
        $this->selected_columns = [];
    }

    public function addColumn($key, $label)
    {
        $this->selected_columns[] = ['key' => $key, 'label' => $label];
    }

    public function removeColumn($index)
    {
        array_splice($this->selected_columns, $index, 1);
        $this->selected_columns = array_values($this->selected_columns);
    }

    public function moveColumn($index, $direction)
    {
        $newIndex = $direction === 'up' ? $index - 1 : $index + 1;
        if ($newIndex < 0 || $newIndex >= count($this->selected_columns)) return;
        $temp = $this->selected_columns[$index];
        $this->selected_columns[$index] = $this->selected_columns[$newIndex];
        $this->selected_columns[$newIndex] = $temp;
    }
}; ?>

<div class="p-4 md:p-8">
    <div class="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 mb-8">
        <div>
            <h2 class="text-3xl font-black text-slate-900 tracking-tighter uppercase">Setting Document Format</h2>
            <p class="text-sm text-slate-500 font-medium">Atur template output untuk berbagai jenis dokumen sistem</p>
        </div>
        @can('setting-document.create')
            <button wire:click="openCreateModal"
                class="flex items-center gap-2 bg-ksc-blue hover:bg-blue-700 text-white px-6 py-3 rounded-2xl font-bold transition shadow-xl shadow-blue-100 transform hover:-translate-y-0.5">
                <x-lucide-file-plus class="w-5 h-5" />
                <span>Tambah Format</span>
            </button>
        @endcan
    </div>

    {{-- Filters --}}
    <div class="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
        <div class="relative">
            <x-lucide-search class="w-5 h-5 absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" />
            <input type="text" wire:model.live.debounce.300ms="search" placeholder="Cari format dokumen..."
                class="w-full pl-12 pr-4 py-3 bg-white border border-slate-200 rounded-2xl text-sm font-medium text-slate-700 focus:ring-4 focus:ring-blue-50 outline-none transition">
        </div>
    </div>

    {{-- Table --}}
    <div class="bg-white border border-slate-100 rounded-[2.5rem] shadow-sm overflow-hidden">
        <div class="overflow-x-auto">
            <table class="w-full text-left border-collapse">
                <thead class="bg-slate-50/50 border-b border-slate-100">
                    <tr>
                        <th class="px-8 py-5 text-[10px] font-black text-slate-400 uppercase tracking-[0.2em]">Format Name</th>
                        <th class="px-8 py-5 text-[10px] font-black text-slate-400 uppercase tracking-[0.2em]">Type</th>
                        <th class="px-8 py-5 text-[10px] font-black text-slate-400 uppercase tracking-[0.2em]">Status</th>
                        <th class="px-8 py-5 text-[10px] font-black text-slate-400 uppercase tracking-[0.2em] text-center">Aksi</th>
                    </tr>
                </thead>
                <tbody class="divide-y divide-slate-50">
                    @forelse($documents as $doc)
                        <tr wire:key="doc-{{ $doc->uid }}" class="hover:bg-slate-50/50 transition group">
                            <td class="px-8 py-6">
                                <div class="flex items-center gap-3">
                                    <div class="w-10 h-10 bg-blue-50 rounded-xl flex items-center justify-center">
                                        <x-lucide-file-text class="text-ksc-blue w-5 h-5" />
                                    </div>
                                    <div>
                                        <span class="text-sm font-black text-slate-900 uppercase tracking-tight block">{{ $doc->name }}</span>
                                        <span class="text-[10px] text-slate-400 font-medium uppercase">{{ $doc->title ?: 'No Title' }}</span>
                                    </div>
                                </div>
                            </td>
                            <td class="px-8 py-6">
                                <span class="px-3 py-1 bg-slate-100 text-slate-500 rounded-lg font-black text-[10px] uppercase tracking-widest border border-slate-200">
                                    {{ $doc->type }}
                                </span>
                            </td>
                            <td class="px-8 py-6">
                                @if($doc->is_public)
                                    <span class="flex items-center gap-1.5 text-emerald-600 font-bold text-[10px] uppercase tracking-widest">
                                        <div class="w-1.5 h-1.5 rounded-full bg-emerald-500"></div>
                                        Public
                                    </span>
                                @else
                                    <span class="flex items-center gap-1.5 text-slate-400 font-bold text-[10px] uppercase tracking-widest">
                                        <div class="w-1.5 h-1.5 rounded-full bg-slate-300"></div>
                                        Private
                                    </span>
                                @endif
                            </td>
                            <td class="px-8 py-6">
                                <div class="flex justify-center gap-2">
                                    @can('setting-document.edit')
                                        <button wire:click="openEditModal('{{ $doc->uid }}')" wire:loading.attr="disabled" wire:target="openEditModal"
                                            class="w-10 h-10 flex items-center justify-center text-slate-400 hover:text-ksc-blue hover:bg-blue-50 rounded-xl transition">
                                            <x-lucide-pencil class="w-5 h-5" />
                                        </button>
                                    @endcan
                                    @can('setting-document.delete')
                                        <button wire:click="confirmDelete('{{ $doc->uid }}')"
                                            class="w-10 h-10 flex items-center justify-center text-slate-400 hover:text-rose-600 hover:bg-rose-50 rounded-xl transition">
                                            <x-lucide-trash-2 class="w-5 h-5" />
                                        </button>
                                    @endcan
                                </div>
                            </td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="4" class="px-8 py-20 text-center text-slate-400 font-bold uppercase tracking-widest text-xs">
                                Tidak ada data format dokumen
                            </td>
                        </tr>
                    @endforelse
                </tbody>
            </table>
        </div>
    </div>

    <div class="mt-6">
        {{ $documents->links() }}
    </div>

    {{-- Modal --}}
    @if($showModal)
        <div class="fixed inset-0 z-[2000] overflow-y-auto px-4 py-6 sm:px-0 flex items-center justify-center">
            <div class="fixed inset-0 transform transition-all" wire:click="$set('showModal', false)">
                <div class="absolute inset-0 bg-slate-900/60 backdrop-blur-sm"></div>
            </div>

            <div class="bg-white rounded-[2.5rem] overflow-hidden shadow-2xl transform transition-all sm:w-full sm:max-w-5xl z-[2010] border border-slate-100">
                <div class="p-8 border-b border-slate-50 flex justify-between items-center bg-slate-50/30">
                    <h3 class="text-xl font-black text-slate-900 tracking-tighter uppercase">
                        {{ $modalMode === 'create' ? 'Tambah Format Baru' : 'Edit Format Dokumen' }}
                    </h3>
                    <button wire:click="$set('showModal', false)" class="text-slate-400 hover:text-slate-600 transition">
                        <x-lucide-x class="w-6 h-6" />
                    </button>
                </div>

                <div class="px-8 pt-4 border-b border-slate-50 flex gap-2 bg-slate-50/10 overflow-x-auto">
                    <button type="button" wire:click="$set('activeTab', 'general')" class="px-5 py-3 text-[10px] font-black uppercase tracking-widest transition-all whitespace-nowrap {{ $activeTab === 'general' ? 'text-blue-600 border-b-2 border-blue-600' : 'text-slate-400 hover:text-slate-600' }}">General</button>
                    <button type="button" wire:click="$set('activeTab', 'content')" class="px-5 py-3 text-[10px] font-black uppercase tracking-widest transition-all whitespace-nowrap {{ $activeTab === 'content' ? 'text-blue-600 border-b-2 border-blue-600' : 'text-slate-400 hover:text-slate-600' }}">Content</button>
                    <button type="button" wire:click="$set('activeTab', 'data_builder')" class="px-5 py-3 text-[10px] font-black uppercase tracking-widest transition-all whitespace-nowrap {{ $activeTab === 'data_builder' ? 'text-blue-600 border-b-2 border-blue-600' : 'text-slate-400 hover:text-slate-600' }}">Data Builder</button>
                    <button type="button" wire:click="$set('activeTab', 'layout')" class="px-5 py-3 text-[10px] font-black uppercase tracking-widest transition-all whitespace-nowrap {{ $activeTab === 'layout' ? 'text-blue-600 border-b-2 border-blue-600' : 'text-slate-400 hover:text-slate-600' }}">Layout</button>
                    <button type="button" wire:click="$set('activeTab', 'preview')" class="px-5 py-3 text-[10px] font-black uppercase tracking-widest transition-all whitespace-nowrap {{ $activeTab === 'preview' ? 'text-blue-600 border-b-2 border-blue-600' : 'text-slate-400 hover:text-slate-600' }}">Preview</button>
                </div>

                <form x-data @submit.prevent="
                    $refs.mdSubmitBtn.disabled = true;
                    $refs.mdSubmitText.classList.add('hidden');
                    $refs.mdLoadingText.classList.remove('hidden');
                    @this.call('save').then(() => {
                        setTimeout(() => {
                            $refs.mdSubmitBtn.disabled = false;
                            $refs.mdSubmitText.classList.remove('hidden');
                            $refs.mdLoadingText.classList.add('hidden');
                        }, 1000);
                    }).catch(() => {
                        $refs.mdSubmitBtn.disabled = false;
                        $refs.mdSubmitText.classList.remove('hidden');
                        $refs.mdLoadingText.classList.add('hidden');
                    });
                " class="p-8">
                    @if($activeTab === 'general')
                        <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                            <div class="space-y-6">
                                <div>
                                    <label class="block text-xs font-black text-slate-400 uppercase tracking-widest mb-2 ml-1">Nama Format</label>
                                    <input type="text" wire:model="name" placeholder="Contoh: Invoice Standar"
                                        class="w-full px-4 py-3 bg-slate-50 border-none rounded-2xl text-sm font-bold text-slate-900 focus:ring-4 focus:ring-blue-100 outline-none transition">
                                    @error('name') <span class="text-[10px] text-rose-500 font-bold ml-1">{{ $message }}</span> @enderror
                                </div>

                                <div>
                                    <label class="block text-xs font-black text-slate-400 uppercase tracking-widest mb-2 ml-1">Jenis Dokumen</label>
                                    <input type="text" wire:model="type" list="document-types" placeholder="Pilih atau ketik jenis baru..."
                                        class="w-full px-4 py-3 bg-slate-50 border-none rounded-2xl text-sm font-bold text-slate-900 focus:ring-4 focus:ring-blue-100 outline-none transition">
                                    <datalist id="document-types">
                                        <option value="result">Hasil Pertandingan</option>
                                        <option value="schedule">Jadwal</option>
                                        <option value="certificate">Sertifikat</option>
                                        <option value="invoice">Invoice</option>
                                        <option value="report">Laporan</option>
                                        <option value="announcement">Pengumuman</option>
                                    </datalist>
                                    @error('type') <span class="text-[10px] text-rose-500 font-bold ml-1">{{ $message }}</span> @enderror
                                </div>

                                <div>
                                    <label class="block text-xs font-black text-slate-400 uppercase tracking-widest mb-2 ml-1">Judul Dokumen (Header)</label>
                                    <input type="text" wire:model="title" placeholder="Contoh: HASIL PERTANDINGAN"
                                        class="w-full px-4 py-3 bg-slate-50 border-none rounded-2xl text-sm font-bold text-slate-900 focus:ring-4 focus:ring-blue-100 outline-none transition">
                                    @error('title') <span class="text-[10px] text-rose-500 font-bold ml-1">{{ $message }}</span> @enderror
                                </div>
                            </div>

                            <div class="space-y-6">
                                <div>
                                    <label class="block text-xs font-black text-slate-400 uppercase tracking-widest mb-2 ml-1">Logo Kiri</label>
                                    <div wire:ignore class="flex items-center gap-4">
                                        <div id="preview_md_logo_left_wrap" class="flex items-center">
                                            @if($existingLogoLeft)
                                                <img id="preview_md_logo_left" src="{{ str_starts_with($existingLogoLeft, 'uploads/') ? asset($existingLogoLeft) : asset('storage/' . $existingLogoLeft) }}" class="w-20 h-20 object-contain rounded-xl border border-slate-100">
                                            @else
                                                <img id="preview_md_logo_left" src="" class="w-20 h-20 object-contain rounded-xl border border-slate-100 hidden">
                                                <div id="placeholder_md_logo_left" class="w-20 h-20 bg-slate-50 rounded-xl flex items-center justify-center border-2 border-dashed border-slate-200">
                                                    <x-lucide-image class="w-8 h-8 text-slate-300" />
                                                </div>
                                            @endif
                                        </div>
                                        <input type="file" id="md_logo_left" class="text-xs text-slate-500 file:mr-4 file:py-2 file:px-4 file:rounded-full file:border-0 file:text-xs file:font-semibold file:bg-blue-50 file:text-blue-700 hover:file:bg-blue-100" onchange="previewSingleImage(this, 'preview_md_logo_left', 'placeholder_md_logo_left'); readAndSetBase64(this, base64 => @this.set('logo_left', base64))">
                                    </div>
                                    @error('logo_left') <span class="text-[10px] text-rose-500 font-bold ml-1">{{ $message }}</span> @enderror
                                </div>

                                <div>
                                    <label class="block text-xs font-black text-slate-400 uppercase tracking-widest mb-2 ml-1">Logo Kanan</label>
                                    <div wire:ignore class="flex items-center gap-4">
                                        <div id="preview_md_logo_right_wrap" class="flex items-center">
                                            @if($existingLogoRight)
                                                <img id="preview_md_logo_right" src="{{ str_starts_with($existingLogoRight, 'uploads/') ? asset($existingLogoRight) : asset('storage/' . $existingLogoRight) }}" class="w-20 h-20 object-contain rounded-xl border border-slate-100">
                                            @else
                                                <img id="preview_md_logo_right" src="" class="w-20 h-20 object-contain rounded-xl border border-slate-100 hidden">
                                                <div id="placeholder_md_logo_right" class="w-20 h-20 bg-slate-50 rounded-xl flex items-center justify-center border-2 border-dashed border-slate-200">
                                                    <x-lucide-image class="w-8 h-8 text-slate-300" />
                                                </div>
                                            @endif
                                        </div>
                                        <input type="file" id="md_logo_right" class="text-xs text-slate-500 file:mr-4 file:py-2 file:px-4 file:rounded-full file:border-0 file:text-xs file:font-semibold file:bg-blue-50 file:text-blue-700 hover:file:bg-blue-100" onchange="previewSingleImage(this, 'preview_md_logo_right', 'placeholder_md_logo_right'); readAndSetBase64(this, base64 => @this.set('logo_right', base64))">
                                    </div>
                                    @error('logo_right') <span class="text-[10px] text-rose-500 font-bold ml-1">{{ $message }}</span> @enderror
                                </div>

                                <div class="flex items-center gap-3 p-4 bg-slate-50 rounded-2xl">
                                    <label class="relative inline-flex items-center cursor-pointer">
                                        <input type="checkbox" wire:model="is_public" class="sr-only peer">
                                        <div class="w-11 h-6 bg-slate-200 peer-focus:outline-none rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-ksc-blue"></div>
                                    </label>
                                    <span class="text-xs font-black text-slate-700 uppercase tracking-widest">Public Format</span>
                                </div>
                            </div>
                        </div>
                    @elseif($activeTab === 'content')
                        <div class="space-y-4">
                            <div>
                                <label class="block text-xs font-black text-slate-400 uppercase tracking-widest mb-2 ml-1">Body Template Content</label>
                                <p class="text-[10px] text-slate-400 mb-4 ml-1 uppercase font-bold tracking-tight">Gunakan placeholder: {event_name}, {event_date}, {club_name}, {current_date}</p>
                                <div wire:ignore>
                                    <textarea id="content-editor" wire:model.defer="content" rows="15" 
                                        class="w-full px-4 py-3 bg-slate-50 border-none rounded-2xl text-sm font-medium text-slate-900 focus:ring-4 focus:ring-blue-100 outline-none transition"></textarea>
                                </div>
                                @error('content') <span class="text-[10px] text-rose-500 font-bold ml-1">{{ $message }}</span> @enderror
                            </div>
                        </div>
                    @elseif($activeTab === 'data_builder')
                        <div class="space-y-6">
                            {{-- Data Source Picker --}}
                            <div>
                                <label class="block text-xs font-black text-blue-600 uppercase tracking-[0.2em] mb-3">Sumber Data</label>
                                <div class="grid grid-cols-2 md:grid-cols-3 gap-3">
                                    @foreach($dataSources as $key => $src)
                                        <button type="button" wire:click="selectSource('{{ $key }}')"
                                            class="p-4 rounded-2xl border-2 transition-all text-left {{ $data_source === $key ? 'bg-blue-600 text-white border-blue-600 shadow-lg shadow-blue-200' : 'bg-white text-slate-600 border-slate-200 hover:border-blue-300' }}">
                                            <span class="text-2xl block mb-1">{{ $src['icon'] }}</span>
                                            <span class="text-[10px] font-black uppercase tracking-widest block">{{ $src['label'] }}</span>
                                            <span class="text-[9px] font-medium opacity-60 block mt-0.5">{{ $src['desc'] }}</span>
                                        </button>
                                    @endforeach
                                </div>
                            </div>

                            {{-- Column Picker --}}
                            @if($data_source)
                                <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                                    {{-- Available Columns --}}
                                    <div>
                                        <label class="block text-xs font-black text-slate-400 uppercase tracking-widest mb-3">Kolom Tersedia</label>
                                        <div class="bg-slate-50 rounded-2xl p-4 space-y-2 max-h-72 overflow-y-auto">
                                            @forelse($availableColumns as $col)
                                                <button type="button" wire:click="addColumn('{{ $col['key'] }}', '{{ $col['label'] }}')"
                                                    class="flex items-center gap-3 w-full px-4 py-2.5 bg-white rounded-xl border border-slate-100 hover:border-blue-300 hover:shadow-sm transition text-left group">
                                                    <span class="w-6 h-6 bg-blue-50 rounded-lg flex items-center justify-center text-blue-600 text-xs font-black group-hover:bg-blue-600 group-hover:text-white transition">+</span>
                                                    <span class="text-xs font-bold text-slate-700">{{ $col['label'] }}</span>
                                                </button>
                                            @empty
                                                <p class="text-[10px] text-slate-400 font-bold text-center py-4 uppercase">Semua kolom sudah dipilih</p>
                                            @endforelse
                                        </div>
                                    </div>

                                    {{-- Selected Columns --}}
                                    <div>
                                        <label class="block text-xs font-black text-slate-400 uppercase tracking-widest mb-3">Kolom Terpilih <span class="text-blue-500">(↑↓ untuk urutkan)</span></label>
                                        <div class="bg-slate-50 rounded-2xl p-4 space-y-2 min-h-[120px] max-h-72 overflow-y-auto">
                                            @forelse($selected_columns as $idx => $col)
                                                <div class="flex items-center gap-2 px-4 py-2.5 bg-white rounded-xl border border-slate-100 shadow-sm group">
                                                    <span class="text-[10px] font-black text-slate-300 w-5 text-center">{{ $idx + 1 }}</span>
                                                    <span class="text-xs font-bold text-slate-700 flex-1">{{ $col['label'] }}</span>
                                                    <button type="button" wire:click="moveColumn({{ $idx }}, 'up')" class="w-6 h-6 flex items-center justify-center text-slate-300 hover:text-blue-500 hover:bg-blue-50 rounded transition text-xs {{ $idx === 0 ? 'opacity-30 pointer-events-none' : '' }}">↑</button>
                                                    <button type="button" wire:click="moveColumn({{ $idx }}, 'down')" class="w-6 h-6 flex items-center justify-center text-slate-300 hover:text-blue-500 hover:bg-blue-50 rounded transition text-xs {{ $idx === count($selected_columns) - 1 ? 'opacity-30 pointer-events-none' : '' }}">↓</button>
                                                    <button type="button" wire:click="removeColumn({{ $idx }})" class="w-6 h-6 flex items-center justify-center text-slate-300 hover:text-rose-500 hover:bg-rose-50 rounded transition text-xs">✕</button>
                                                </div>
                                            @empty
                                                <p class="text-[10px] text-slate-400 font-bold text-center py-8 uppercase">Pilih kolom dari daftar di kiri</p>
                                            @endforelse
                                        </div>
                                    </div>
                                </div>
                            @endif
                        </div>

                    @elseif($activeTab === 'layout')
                        <div class="grid grid-cols-1 md:grid-cols-2 gap-8">
                            <div class="space-y-6">
                                <h4 class="text-xs font-black text-blue-600 uppercase tracking-[0.2em] mb-4">Page & Typography</h4>
                                <div class="grid grid-cols-2 gap-4 mb-4">
                                    <div>
                                        <label class="block text-[10px] font-black text-slate-400 uppercase mb-2">Page Size</label>
                                        <select wire:model="page_size" class="w-full px-4 py-2 bg-slate-50 border-none rounded-xl text-xs font-bold">
                                            <option value="A4">A4</option>
                                            <option value="Letter">Letter</option>
                                            <option value="Legal">Legal</option>
                                        </select>
                                    </div>
                                    <div>
                                        <label class="block text-[10px] font-black text-slate-400 uppercase mb-2">Orientation</label>
                                        <select wire:model="page_orientation" class="w-full px-4 py-2 bg-slate-50 border-none rounded-xl text-xs font-bold">
                                            <option value="portrait">Portrait</option>
                                            <option value="landscape">Landscape</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="grid grid-cols-2 gap-4 mb-4">
                                    <div>
                                        <label class="block text-[10px] font-black text-slate-400 uppercase mb-2">Font Family</label>
                                        <select wire:model="font_family" class="w-full px-4 py-2 bg-slate-50 border-none rounded-xl text-xs font-bold">
                                            <option value="Arial">Arial</option>
                                            <option value="Montserrat">Montserrat</option>
                                            <option value="Roboto">Roboto</option>
                                            <option value="Times New Roman">Times New Roman</option>
                                        </select>
                                    </div>
                                    <div>
                                        <label class="block text-[10px] font-black text-slate-400 uppercase mb-2">Font Size (pt)</label>
                                        <input type="number" wire:model="font_size" class="w-full px-4 py-2 bg-slate-50 border-none rounded-xl text-xs font-bold">
                                    </div>
                                </div>
                                <div class="flex items-center justify-between p-3 bg-slate-50 rounded-xl">
                                    <span class="text-[10px] font-black text-slate-600 uppercase">Show Header</span>
                                    <input type="checkbox" wire:model="layout_settings.header.show" class="rounded border-slate-300 text-blue-600">
                                </div>
                            </div>
                            <div class="space-y-6">
                                <h4 class="text-xs font-black text-blue-600 uppercase tracking-[0.2em] mb-4">Table & Footer</h4>
                                <div class="flex items-center justify-between p-3 bg-slate-50 rounded-xl">
                                    <span class="text-[10px] font-black text-slate-600 uppercase">Zebra Striping</span>
                                    <input type="checkbox" wire:model="layout_settings.table.zebra" class="rounded border-slate-300 text-blue-600">
                                </div>
                                <div class="flex items-center justify-between p-3 bg-slate-50 rounded-xl">
                                    <span class="text-[10px] font-black text-slate-600 uppercase">Show Footer</span>
                                    <input type="checkbox" wire:model="layout_settings.footer.show" class="rounded border-slate-300 text-blue-600">
                                </div>
                                <div>
                                    <label class="block text-[10px] font-black text-slate-400 uppercase mb-2">Footer Text</label>
                                    <input type="text" wire:model="layout_settings.footer.text" class="w-full px-4 py-2 bg-slate-50 border-none rounded-xl text-xs font-bold">
                                </div>
                            </div>
                        </div>
                    @elseif($activeTab === 'preview')
                        <div class="bg-slate-800 p-8 rounded-[2rem] overflow-hidden">
                            <div class="bg-white shadow-2xl mx-auto w-full aspect-[1/1.414] max-w-2xl origin-top scale-90 sm:scale-100 transition-all p-[1cm] text-slate-900" 
                                style="min-height: 842px; font-family: '{{ $font_family }}', sans-serif; font-size: {{ $font_size }}pt;">
                                
                                {{-- Header Preview --}}
                                @if($layout_settings['header']['show'])
                                    <div class="flex items-center justify-between border-b-2 border-slate-900 pb-4 mb-8">
                                        <div class="w-20">
                                            @if($layout_settings['header']['show_logo_left'])
                                                @if($existingLogoLeft)
                                                    <img src="{{ asset('storage/' . $existingLogoLeft) }}" class="w-16 h-16 object-contain">
                                                @else
                                                    <img id="preview_tab_logo_left" src="" class="w-16 h-16 object-contain hidden">
                                                @endif
                                            @endif
                                        </div>
                                        <div class="text-center flex-1">
                                            <h4 class="text-lg font-bold uppercase">{{ $title ?: 'JUDUL DOKUMEN' }}</h4>
                                            <p class="text-sm font-medium">{{ $description ?: 'Deskripsi atau alamat event akan muncul di sini...' }}</p>
                                        </div>
                                        <div class="w-20 text-right">
                                            @if($layout_settings['header']['show_logo_right'])
                                                @if($existingLogoRight)
                                                    <img src="{{ asset('storage/' . $existingLogoRight) }}" class="w-16 h-16 object-contain ml-auto">
                                                @else
                                                    <img id="preview_tab_logo_right" src="" class="w-16 h-16 object-contain ml-auto hidden">
                                                @endif
                                            @endif
                                        </div>
                                    </div>
                                @endif

                                {{-- Body Preview --}}
                                <div class="space-y-6">
                                    <h5 class="text-center font-bold underline uppercase">{{ strtoupper($type ?: 'CONTOH') }}</h5>
                                    
                                    @if($content)
                                        <div class="text-xs leading-relaxed">{!! $content !!}</div>
                                    @endif

                                    @if(count($selected_columns) > 0)
                                        <table class="w-full text-xs border-collapse {{ $layout_settings['table']['show_border'] ? 'border border-slate-900' : '' }}">
                                            <thead>
                                                <tr class="bg-slate-100">
                                                    @foreach($selected_columns as $col)
                                                        <th class="border border-slate-900 p-1 px-2 text-left">{{ $col['label'] }}</th>
                                                    @endforeach
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @for($i = 0; $i < 3; $i++)
                                                    <tr class="{{ $layout_settings['table']['zebra'] && $i % 2 === 1 ? 'bg-slate-50' : 'bg-white' }}">
                                                        @foreach($selected_columns as $col)
                                                            <td class="border border-slate-900 p-1 px-2">
                                                                @switch($col['key'])
                                                                    @case('rank') @case('no') @case('lane') {{ $i + 1 }} @break
                                                                    @case('athlete_name') {{ ['ARVINO NAZZRIL S.','M NAUFAL ABI P.','AZKA WILDAN S.'][$i] }} @break
                                                                    @case('club_name') {{ ['ORCA AQUATIQ','HAYAM WURUK AC','SWORDFISH AC'][$i] }} @break
                                                                    @case('time') @case('seed_time') @case('result') {{ ['01:00.34','00:58.60','NT'][$i] }} @break
                                                                    @case('birth_year') 2017 @break
                                                                    @case('category') KU 2017 @break
                                                                    @case('style') 50M GAYA BEBAS @break
                                                                    @case('status') {{ ['Verified','Pending','Draft'][$i] }} @break
                                                                    @case('total') {{ ['Rp 500.000','Rp 750.000','Rp 300.000'][$i] }} @break
                                                                    @case('invoice_no') INV-{{ str_pad($i+1,4,'0',STR_PAD_LEFT) }} @break
                                                                    @case('method') {{ ['Transfer','Cash','QRIS'][$i] }} @break
                                                                    @case('date') 08/02/2026 @break
                                                                    @case('heat') Seri {{ $i + 1 }} @break
                                                                    @case('points') {{ [25,18,15][$i] }} @break
                                                                    @case('coach') Coach {{ $i + 1 }} @break
                                                                    @case('total_athletes') {{ [12,8,15][$i] }} @break
                                                                    @case('phone') 08123456789{{ $i }} @break
                                                                    @case('address') Jl. Contoh No.{{ $i+1 }} @break
                                                                    @case('event_name') Event Contoh {{ $i+1 }} @break
                                                                    @case('location') GOR Sidoarjo @break
                                                                    @case('total_categories') {{ [10,8,12][$i] }} @break
                                                                    @default {{ $col['label'] }} {{ $i+1 }} @break
                                                                @endswitch
                                                            </td>
                                                        @endforeach
                                                    </tr>
                                                @endfor
                                            </tbody>
                                        </table>
                                    @else
                                        <p class="text-xs text-center text-slate-400 italic py-8">Pilih kolom di tab "Data Builder" untuk melihat tabel preview.</p>
                                    @endif
                                </div>

                                {{-- Footer Preview --}}
                                @if($layout_settings['footer']['show'])
                                    <div class="absolute bottom-[1cm] left-[1cm] right-[1cm] border-t border-slate-200 pt-2 flex justify-between text-[8px] italic text-slate-400">
                                        <span>{{ $layout_settings['footer']['text'] }}</span>
                                        <span>Halaman 1 dari 1</span>
                                    </div>
                                @endif
                            </div>
                        </div>
                    @endif

                    <div class="flex items-center pt-8 mt-8 border-t border-slate-100 gap-4">
                        <button type="button" wire:click="$set('showModal', false)"
                            class="flex-1 px-6 py-4 bg-slate-100 text-slate-600 rounded-2xl font-bold hover:bg-slate-200 transition">Batal</button>
                        <button type="submit" x-ref="mdSubmitBtn"
                            class="flex-1 px-6 py-4 bg-ksc-blue text-white rounded-2xl font-bold hover:bg-blue-700 transition shadow-xl shadow-blue-100 flex items-center justify-center gap-2 disabled:opacity-70 disabled:cursor-not-allowed">
                            <span x-ref="mdSubmitText">
                                {{ $modalMode === 'create' ? 'Simpan Data' : 'Perbarui Data' }}
                            </span>
                            <span x-ref="mdLoadingText" class="hidden flex items-center gap-2">
                                <svg class="animate-spin h-4 w-4 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                                    <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
                                    <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                                </svg>
                                <span>Memproses...</span>
                            </span>
                        </button>
                    </div>
                </form>
            </div>
        </div>
    @endif

    {{-- Modal Delete Confirmation --}}
    @if ($showDeleteModal)
        <div class="fixed inset-0 z-[2000] overflow-y-auto px-4 py-6 sm:px-0 flex items-center justify-center">
            <div class="fixed inset-0 transform transition-all" wire:click="$set('showDeleteModal', false)">
                <div class="absolute inset-0 bg-slate-900/60 backdrop-blur-sm"></div>
            </div>

            <div
                class="bg-white rounded-[2.5rem] overflow-hidden shadow-2xl transform transition-all sm:w-full sm:max-w-md z-[2010] border border-slate-100">
                <div class="p-12 text-center">
                    <div
                        class="w-20 h-20 bg-rose-50 rounded-[2.5rem] flex items-center justify-center mx-auto mb-8 shadow-xl shadow-rose-100">
                        <x-lucide-alert-circle class="w-10 h-10 text-rose-600" />
                    </div>
                    <h3 class="text-2xl font-black text-slate-900 tracking-tighter uppercase mb-4">Hapus Format?</h3>
                    <p class="text-slate-500 font-medium mb-10 px-10 leading-relaxed uppercase text-[10px] tracking-widest">Format <span
                            class="text-rose-600 font-black">"{{ $documentToDelete?->name }}"</span>
                        akan dihapus permanen dari sistem.</p>
                    <div class="flex flex-col sm:flex-row gap-4 justify-center">
                        <button wire:click="$set('showDeleteModal', false)"
                            class="px-8 py-4 bg-slate-100 text-slate-600 rounded-2xl font-bold hover:bg-slate-200 transition uppercase text-[10px] tracking-widest flex-1">Batal</button>
                        <button wire:click="delete" wire:loading.attr="disabled" wire:target="delete"
                            class="px-8 py-4 bg-rose-600 text-white rounded-2xl font-bold hover:bg-rose-700 transition shadow-xl shadow-rose-200 flex items-center justify-center gap-2 min-w-[160px] uppercase text-[10px] tracking-widest flex-1">
                            <span wire:loading.remove wire:target="delete">Ya, Hapus</span>
                            <span wire:loading wire:target="delete" class="flex items-center gap-2">
                                <svg class="animate-spin h-4 w-4 text-white" xmlns="http://www.w3.org/2000/svg"
                                    fill="none" viewBox="0 0 24 24">
                                    <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor"
                                        stroke-width="4"></circle>
                                    <path class="opacity-75" fill="currentColor"
                                        d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z">
                                    </path>
                                </svg>
                            </span>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    @endif
</div>

